defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  # git-init uses a base image that supports running either as root or as user nonroot with UID 65532.
  github.com/tektoncd/pipeline/cmd/git-init: gcr.io/tekton-nightly/github.com/ouyang-xlauncher/pipeline/git-init-build-base:latest

  # PullRequest resource uses a distroless base image that supports running either as root or as user nonroot with UID 65532.
  github.com/tektoncd/pipeline/cmd/pullrequest-init: gcr.io/tekton-nightly/github.com/ouyang-xlauncher/pipeline/pullrequest-init-build-base:latest
